--CREATE TABLE with default value to isFEMALE
CREATE TABLE EMP_TEST
( EMP_ID NUMBER,
  PERF_FACTOR NUMBER(3,2),
  BIRTH_DATE DATE,
  NAME VARCHAR2(30),
  ISFEMALE CHAR(1) DEFAULT 'Y');
  
-- USER_TABLES : Query to get info of table you own
-- ALL_TABLES: USER_TABLES + tables you have been given access to.


---- CONSTRAINTS: UNIQUE, NULL, CHECK, PRIMARY, FOREIGN
 CREATE TABLE STUD
 ( STUD_ID VARCHAR(20) CONSTRAINT STUD_PK PRIMARY KEY,
   NUMBER MARKS CONSTRAINT STUD_MARKS_CHECK CHECK(MARKS >20),
   NAME VARCHAR(20) NOT NULL,
   ROLL_NUM VARCHAR(20) UNIQUE
   DEPT_ID VARCHAR(30) CONSTRAINT STUD_FK REFERENCES DEPARTMENT(DEPT_ID));
