------INSERT STMTS
INSERT INTO HR.DEPARTMENTS(DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID)
VALUES(71, 'ESH_DEPT', 100, 1700);

--NULL VALUES CAN BE TREATED AS VAR ARGS AND CAN BE OMITTED FROM THE VALUE ASGNMT OR YOU CAN EXPLICTLY INSERT NULLS
INSERT INTO HR.DEPARTMENTS VALUES(71, 'ESH_DEPT', 100, 1700);

-- WE CAN USE EXPRESSSIONS LIKE SYSDATE, TO_DATE() FUNCTIONS WHILE INSERTING VALUE

--USERS TO INPUT DATA USSING &
INSERT INTO HR.DEPARTMENTS(DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES(&dept_id, &dept_name)

--INSERT USING SELECT
INSERT INTO HR.DEPARTMENTS(DEPARTMENT_ID, DEPARTMENT_NAME)
SELECT DEPARTMENT_ID, DEPARTMENT_NAME
FROM HR.DEPARTMENTS;

--INSERTING EXISTING VALUE: UNIQUE CONSTRAINT VIOLATED

--INSERTING FK VALUE NOT EXISTS IN PARENT TABLE: INTEGRITY CONSTRAINT VIOLATED

--INSERTING DATA OF DIFFERENT DATA TYPE, FOR EX: INSERTING STRING FOR NUMBER: INVALID NUMBER

-- INSERTING VALUE MORE THAN LENGTH OF COLUMN: VALUE TOO LARGE
