
--MAX AND MIN FUNCTIONS

--NUMERIC COLUMN
SELECT MAX(SALARY), MIN(SALARY)
FROM HR.EMPLOYEES;

--VARCHAR COLUMN
SELECT MAX(FIRST_NAME), MIN(LAST_NAME)
FROM HR.EMPLOYEES;

-- DATE COLUMN
SELECT MAX(HIRE_DATE), MIN(HIRE_DATE)
FROM HR.EMPLOYEES;
