--- Multi table queryies

--CARTESIAN PRODUCT: JOIN BETWEEN TWO TABLE WITHOUT ANY CONDITION 
SELECT EMPLOYEE_ID, DEPARTMENT_NAME
FROM HR.EMPLOYEES, HR.DEPARTMENTS
ORDER BY EMPLOYEE_ID;
-- NEW SYNTAX
    SELECT EMPLOYEE_ID, DEPARTMENT_NAME
    FROM HR.EMPLOYEES
    CROSS JOIN
    HR.DEPARTMENTS
    ORDER BY EMPLOYEE_ID;


--Equi Join: using foreign key = primary key
SELECT EMPLOYEE_ID,SALARY, DEPARTMENT_NAME
FROM HR.EMPLOYEES, HR.DEPARTMENTS 
WHERE HR.EMPLOYEES.DEPARTMENT_ID = HR.DEPARTMENTS.DEPARTMENT_ID;
    -- NATURAL JOIN : JOIN USING COLUMNS OF TABLES HAVING SAME NAME
    SELECT EMPLOYEE_ID,SALARY, DEPARTMENT_NAME
    FROM HR.EMPLOYEES
    NATURAL JOIN
    HR.DEPARTMENTS; 
        -- USING : MULTIPLE COLUMNS WITH SAME NAME. SPECIFY THE COLUMN NAME
        SELECT EMPLOYEE_ID,SALARY, DEPARTMENT_NAME
        FROM HR.EMPLOYEES
        JOIN
        HR.DEPARTMENTS
        USING(DEPARTMENT_ID); 
            --ON CLAUSE
            SELECT EMPLOYEE_ID,SALARY, DEPARTMENT_NAME, CITY
            FROM HR.EMPLOYEES
            JOIN
            HR.DEPARTMENTS
            ON
            HR.EMPLOYEES.DEPARTMENT_ID = HR.DEPARTMENTS.DEPARTMENT_ID
            JOIN
            HR.LOCATIONS
            ON
            HR.DEPARTMENTS.LOCATION_ID = HR.LOCATIONS.LOCATION_ID;
            
    

-- NON EQUI JOIN: CARTESIAN PRODUCT WITH SOME OTHER CONDITION IN WHERE CLAUSE
SELECT EMPLOYEE_ID, DEPARTMENT_NAME
FROM HR.EMPLOYEES, HR.DEPARTMENTS
WHERE EMPLOYEE_ID > 200
ORDER BY EMPLOYEE_ID;

-- OUTER JOIN: LEFT OUTER JOIN + RIGHT OUTER JOIN
-- LEFT OUTER JOIN
SELECT EMPLOYEE_ID, SALARY, DEPARTMENT_NAME
FROM HR.EMPLOYEES, HR.DEPARTMENTS 
WHERE HR.EMPLOYEES.DEPARTMENT_ID = HR.DEPARTMENTS.DEPARTMENT_ID(+)
ORDER BY DEPARTMENT_NAME NULLS FIRST;
    -- USING ON
    SELECT EMPLOYEE_ID, SALARY, DEPARTMENT_NAME
    FROM HR.EMPLOYEES
    LEFT OUTER JOIN
    HR.DEPARTMENTS 
    ON HR.EMPLOYEES.DEPARTMENT_ID = HR.DEPARTMENTS.DEPARTMENT_ID
    ORDER BY DEPARTMENT_NAME NULLS FIRST;

-- RIGHT JOIN
SELECT EMPLOYEE_ID, SALARY, DEPARTMENT_NAME
FROM HR.EMPLOYEES, HR.DEPARTMENTS 
WHERE HR.EMPLOYEES.DEPARTMENT_ID(+) = HR.DEPARTMENTS.DEPARTMENT_ID
ORDER BY EMPLOYEE_ID NULLS FIRST;
     -- USING ON
    SELECT EMPLOYEE_ID, SALARY, DEPARTMENT_NAME
    FROM HR.EMPLOYEES
    RIGHT OUTER JOIN
    HR.DEPARTMENTS 
    ON HR.EMPLOYEES.DEPARTMENT_ID = HR.DEPARTMENTS.DEPARTMENT_ID
    ORDER BY EMPLOYEE_ID NULLS FIRST;

--SELF JOIN
SELECT EMP.FIRST_NAME AS "EMPLOYEE_FIRST_NAME",  MGR.FIRST_NAME AS "MANAGER_FIRST_NAME"
FROM (HR.EMPLOYEES) EMP, (HR.EMPLOYEES)  MGR 
WHERE EMP.EMPLOYEES_ID = MGR.MANAGER_ID 





