DECLARE
    l_NAME HR.EMPLOYEES.FIRST_NAME%TYPE;
BEGIN 
    SELECT FIRST_NAME 
    INTO l_NAME
    FROM HR.EMPLOYEES
    WHERE EMPLOYEE_ID = 100;
    
    IF L_NAME LIKE '%ESHITA%' THEN
        DBMS_OUTPUT.put_line('NAME IS ESHITA');
    ELSE
         DBMS_OUTPUT.put_line('MAY BE STEVEN');
    END IF;  
  
    EXCEPTION
        WHEN ZERO_DIVIDE THEN
            DBMS_OUTPUT.put_line(SQLERRM);
END;
