--UNION: ALL RECORDS FROM BOTH SETS EXCEPT DUPLICATES
SELECT EMPLOYEE_ID, FIRST_NAME, DEPARTMENT_ID
FROM HR.EMPLOYEES
WHERE DEPARTMENT_ID =90
UNION 
SELECT EMPLOYEE_ID, FIRST_NAME, DEPARTMENT_ID
FROM HR.EMPLOYEES
WHERE DEPARTMENT_ID =60

--UNION ALL: ALL RECORDS FROM BOOTH SETS INCLUDING DUPLICATES
SELECT EMPLOYEE_ID, FIRST_NAME, DEPARTMENT_ID
FROM HR.EMPLOYEES
WHERE DEPARTMENT_ID =90
UNION ALL
SELECT EMPLOYEE_ID, FIRST_NAME, DEPARTMENT_ID
FROM HR.EMPLOYEES
WHERE DEPARTMENT_ID =60

--INTERSECT: COMMON RECORDS
SELECT EMPLOYEE_ID, FIRST_NAME, DEPARTMENT_ID
FROM HR.EMPLOYEES
WHERE DEPARTMENT_ID =90
INTERSECT
SELECT EMPLOYEE_ID, FIRST_NAME, DEPARTMENT_ID
FROM HR.EMPLOYEES
WHERE DEPARTMENT_ID =60

--MINUS: RECORDS OF A - RECORDS OF B
SELECT EMPLOYEE_ID, FIRST_NAME, DEPARTMENT_ID
FROM HR.EMPLOYEES
WHERE DEPARTMENT_ID =90
MINUS
SELECT EMPLOYEE_ID, FIRST_NAME, DEPARTMENT_ID
FROM HR.EMPLOYEES
WHERE DEPARTMENT_ID =60
