
--SINGLE ROW FUNCTIONS : RETURN ONE RESULT PER ROW
/*
TYPES: CHARACTER(LOWER, UPPER, INITCAP, CONCAT, SUBSTR, LENGTH, INSTR, LPAD, RPAD, TRIM, REPLACE),
         NUMBER(ROUNF, TRUNC, MOD),
         DATE(MONTHS_BETWEEN, ADD_MONTHS, NEXT_DAY, LAST_DAY, ROUND, TRUNC),
         CONVERSION(TO_DATE, TO_CHAR),
         GENERAL(NVL, NVL2, NULLIF, COAELSCE, DECODE, CASE)
*/
