---------------SINGLE ROW SUBQUERIES
--select employees who salary > salary of abel
SELECT EMPLOYEE_ID, FIRST_NAME
FROM HR.EMPLOYEES
WHERE SALARY > (SELECT SALARY FROM HR.EMPLOYEES WHERE LAST_NAME ='Abel')

-- SELECT EMPLOYEE HAVING MAX SALARY
SELECT * 
FROM HR.EMPLOYEES
WHERE SALARY = (SELECT MAX(SALARY) FROM HR.EMPLOYEES);

--GET COUNT OF EMPLOYEE ID BY DEPARTMENT BUT ONLY DEPARTMENETS HAVING COUNT > COUNT OF DEPARTMENT 90
SELECT COUNT(EMPLOYEE_ID), DEPARTMENT_ID
FROM HR.EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING COUNT(EMPLOYEE_ID) > (SELECT COUNT(*) FROM HR.EMPLOYEES WHERE DEPARTMENT_ID = 90)

-- IF A SSUBQUERY RETURN NULL VALUE, COMPLETE QUERY WILL RETURN NULL VALUE


---------------MULTIPLE ROW SUBQUERIES : IS, ANY, ALL
-- IN/NOT IN clause  Not in returns empty if null value present
SELECT * 
FROM HR.EMPLOYEES
WHERE SALARY IN (SELECT SALARY FROM HR.EMPLOYEES WHERE DEPARTMENT_ID = 90)

--ANY CLAUSE - IF SALARY MATCHES ONE OF THEM
SELECT * 
FROM HR.EMPLOYEES
WHERE SALARY > ANY(SELECT SALARY FROM HR.EMPLOYEES WHERE DEPARTMENT_ID = 90)

--ALL CLAUSE - IF SALARY GREATER THAN ALL OF THEM
SELECT * 
FROM HR.EMPLOYEES
WHERE SALARY > ALL(SELECT SALARY FROM HR.EMPLOYEES WHERE DEPARTMENT_ID = 90)

--EXISTS/NOT EXISTS - USE EXISTS INSTEAD OF IN CLAUSE
SELECT *
FROM HR.DEPARTMENTS
WHERE EXISTS (SELECT EMPLOYEE_ID
              FROM HR.EMPLOYEES 
              JOIN HR.DEPARTMENTS 
              ON HR.EMPLOYEES.DEPARTMENT_ID = HR.DEPARTMENTS.DEPARTMENT_ID) 
              

--USING SUBQUERY AS SOURCE TABLE: SUBQUERY INLINE VIEW
SELECT EMPLOYEE_ID, FIRST_NAME, DEPT.DEPARTMENT_ID, DEPT.DEPARTMENT_NAME
FROM HR.EMPLOYEES,
(SELECT DEPARTMENT_ID, DEPARTMENT_NAME FROM HR.DEPARTMENTS) DEPT
WHERE HR.EMPLOYEES.DEPARTMENT_ID = DEPT.DEPARTMENT_ID;

-- DISPLAY DETAILS OF EMPLOYEES WHO ARE MANAGED BY SAME MANAGER AND WORK IN SAME DEPARTMENT AS THE EMPLOYEES WITH FIRST NAME "JOHN"
SELECT * FROM HR.EMPLOYEES WHERE (MANAGER_ID,DEPARTMENT_ID) IN 
(SELECT MANAGER_ID, DEPARTMENT_ID FROM HR.EMPLOYEES WHERE FIRST_NAME='John')




