---------------SINGLE ROW SUBQUERIES
--select employees who salary > salary of abel
SELECT EMPLOYEE_ID, FIRST_NAME
FROM HR.EMPLOYEES
WHERE SALARY > (SELECT SALARY FROM HR.EMPLOYEES WHERE LAST_NAME ='Abel')

-- SELECT EMPLOYEE HAVING MAX SALARY
SELECT * 
FROM HR.EMPLOYEES
WHERE SALARY = (SELECT MAX(SALARY) FROM HR.EMPLOYEES);

--GET COUNT OF EMPLOYEE ID BY DEPARTMENT BUT ONLY DEPARTMENETS HAVING COUNT > COUNT OF DEPARTMENT 90
SELECT COUNT(EMPLOYEE_ID), DEPARTMENT_ID
FROM HR.EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING COUNT(EMPLOYEE_ID) > (SELECT COUNT(*) FROM HR.EMPLOYEES WHERE DEPARTMENT_ID = 90)

-- IF A SSUBQUERY RETURN NULL VALUE, COMPLETE QUERY WILL RETURN NULL VALUE


---------------MULTIPLE ROW SUBQUERIES : IS, ANY, ALL
-- IN clause 
SELECT * 
FROM HR.EMPLOYEES
WHERE SALARY IN (SELECT SALARY FROM HR.EMPLOYEES WHERE DEPARTMENT_ID = 90)

--ANY CLAUSE - IF SALARY MATCHES ONE OF THEM
SELECT * 
FROM HR.EMPLOYEES
WHERE SALARY > ANY(SELECT SALARY FROM HR.EMPLOYEES WHERE DEPARTMENT_ID = 90)

--ALL CLAUSE - IF SALARY GREATER THAN ALL OF THEM
SELECT * 
FROM HR.EMPLOYEES
WHERE SALARY > ALL(SELECT SALARY FROM HR.EMPLOYEES WHERE DEPARTMENT_ID = 90)

